[JenkinsFile] deploy navitia on artemis with jenkinsfile
CanalTP/fabric_navitia pull request #317
Opened 2020-11-26 17:03 UTC by benoit-bst

- adapt github script to simplify actions
- create jenkinsfile to deploy navitia on artemis machine

related to : https://github.com/CanalTP/jenkins_conf/pull/65 (the job within the new jenkins)

2020-11-27 08:36 UTC, xlqian commented on scripts/retreive_debian_packages_from_github.py
> +    zip = zipfile.ZipFile(path_to_artifacts)
you may use `with ZipFile('spam.zip') as myzip:` so that you won't need to close the file...

2020-11-27 08:40 UTC, xlqian reviewed
just minor

2020-11-27 08:40 UTC, xlqian commented on scripts/retreive_debian_packages_from_github.py
> +    zip = zipfile.ZipFile(path_to_artifacts)
in this case, you need to do `with ZipeFile` twice

2020-11-27 08:40 UTC, xlqian commented on scripts/retreive_debian_packages_from_github.py
> +    zip.extractall()
oops, zip is not closed :p

2020-11-27 08:40 UTC, xlqian commented on .jenkins/deploy_navitia_on_artemis
> +            steps {
you probably need a virtuelenv to no to pollute host env (or a docker)...

2020-11-27 09:08 UTC, benoit-bst commented on .jenkins/deploy_navitia_on_artemis
> +            steps {
Actually it is more complex.
We don’t have root permission and sudo isn’t  installed. Safety first !
So, Installed new stuff is hard.
The best way, is to use a docker environment to run scripts.
I’ll do it in a new PR

2020-11-27 09:09 UTC, benoit-bst commented on scripts/retreive_debian_packages_from_github.py
> +    zip = zipfile.ZipFile(path_to_artifacts)
I have seen it was a python3 way.

2020-11-27 10:30 UTC, xlqian commented on .jenkins/deploy_navitia_on_artemis
> +            steps {
have you tried this? :https://github.com/CanalTP/navitia_deployment_conf/pull/785/files#diff-32159342cc825c75658e2ae6deedb476cd238991854396b4044118375bf68f4cR24

2020-11-27 13:22 UTC, benoit-bst commented on .jenkins/deploy_navitia_on_artemis
> +            steps {
dunno that ? It is a special env like virtenv ?

2020-11-30 10:43 UTC, nonifier requested changes

2020-11-30 10:43 UTC, nonifier commented on .jenkins/deploy_navitia_on_artemis
> +                        python2.7 scripts/retreive_debian_packages_from_github.py -u jenkins-kisio-core -t $GITHUB_TOKEN -w "Build Navitia Packages For Dev" -a artifacts.zip -o "."
We should be using `Build Navitia Packages For Dev Multi Distributions` instead. 
`Build Navitia Packages For Dev` is meant to be removed.

https://github.com/CanalTP/navitia/actions/runs/355479021

2020-12-01 09:51 UTC, xlqian reviewed
I'm Ok with the code but have just some thought about where to host the jenkins file.

2020-12-01 18:09 UTC, nonifier approved these changes
I agree to merge this as it is, and move forward from here !

2020-12-01 18:09 UTC, nonifier commented on .jenkins/deploy_navitia
> +                        '''
In a later version, it would be interesting to only have something 1 line like :
```sh
    sh 'PYTHONPATH=navitia_deployment_conf/ python -u -m fabric use:$PLATFORM upgrade_all:check_version=False'
```

2020-12-01 18:09 UTC, nonifier commented on .jenkins/deploy_navitia
> +    post {
Minor - If you want to be friendly with the ops, you can clean the workspace directory to spare disk space
```
post {
    always {
        cleanWs()
    }
}
```

2020-12-04 09:10 UTC, benoit-bst commented
Waiting if we change the script or not

2020-12-15 14:09 UTC, closed without merging